const ACTIONS = {

    REGISTER: {
        USER_REGISTRATION_PENDING: "USER_REGISTRATION_PENDING",
        USER_REGISTRATION_SUCCESS: "USER_REGISTRATION_SUCCESS",
        USER_REGISTRATION_FAILED: "USER_REGISTRATION_FAILED",
    },
    ACCOUNTS: {
        GET_ACCOUNTS_SUCCESS: "GET_ACCOUNTS_SUCCESS",
        GET_ACCOUNTS_ERROR: "GET_ACCOUNTS_ERROR"
    }

}
export default ACTIONS;